name: PR Source Code Check

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '20'
          cache: 'yarn'
      - run: yarn
      - run: yarn lint

  tsc:
    name: Run Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '20'
          cache: 'yarn'
      - run: yarn
      - run: yarn tsc

  prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '20'
          cache: 'yarn'
      - run: yarn
      - run: yarn format

  stylelint:
    name: Run Stylelint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install packages
        run: yarn
      - name: Run stylelint
        run: yarn stylelint
